epsilon:
  build: .
  command: "./docker/run.sh"
  ports:
   - "31415:31415"
  volumes:
   - .:/epsilon
  links:
   - postgres
  environment:
    - CONTEST # Resolves to the host
    - AUTOJUDGE
    - DEBUG
  privileged: true
  entrypoint: "/epsilon/docker/entrypoint.sh"
postgres:
  image: postgres:9.4
  ports:
   - "5432"