epsilon:
  build: .
  command: "./docker/run.sh"
  ports:
   - "31415:31415"
  volumes:
   - .:/epsilon
   - /sys/fs/cgroup:/sys/fs/cgroup
  links:
   - postgres
  environment:
    - CONTEST # Resolves to the host
    - DEBUG
    - OPTS
  privileged: true
  entrypoint: "/epsilon/docker/entrypoint.sh"
postgres:
  image: postgres:9.4.0
  ports:
   - "5432"
