#!/bin/bash

if [ -z $CONTEST ]; then
    echo "Please set \$CONTEST to continue"
    exit 0
fi

if [ -z $NAME ]; then
    echo "Please set \$NAME to continue"
    exit 0
fi

EPSILON_IMAGE=${EPSILON_IMAGE:-epsilon_epsilon}
docker run -t -i-e CONTEST=$CONTEST \
    --volumes-from=epsilon-data -v /sys/fs/cgroup:/sys/fs/cgroup --privileged=true \
    --link epsilon-postgres:postgres --entrypoint=/epsilon/docker/entrypoint.sh \
    --name "epsilon-judge-$NAME" -d $EPSILON_IMAGE autojudge $@
