#!/bin/bash
relpath(){ python -c "import os.path; print(os.path.relpath('$1','${2:-$PWD}'))" ; } 
fixperms(){ docker exec -i "epsilon-manual-$USER" chmod -R 777 /judging; }
limitjudge() { 

    if [[ ! $PWD/ = $HOME/judging/* ]]; then
        echo "This command must be run from within $HOME/judging"
        exit 0
    fi
}
case $1 in
    "create")
        if [ -z $CONTEST ]; then
            echo "Please set \$CONTEST to continue"
            exit 0
        fi

        if [ -z $USER ]; then
            echo "Please set \$USER to continue"
            exit 0
        fi
        echo "Creating directory $HOME/judging"
        echo "Please run your judging session from there"
        mkdir -p "judging"
        EPSILON_IMAGE=${EPSILON_IMAGE:-epsilon_epsilon}
        docker run -t -i -e CONTEST=$CONTEST \
            --volumes-from=epsilon-data -v /sys/fs/cgroup:/sys/fs/cgroup --privileged=true \
            --link epsilon-postgres:postgres --entrypoint=/epsilon/docker/entrypoint.sh \
            -v "$HOME/judging":/judging -w /judging --name "epsilon-manual-$USER" \
            -d $EPSILON_IMAGE /bin/bash
    ;;
    "stop")
        docker stop "epsilon-manual-$USER"
    ;;
    "start")
        docker start "epsilon-manual-$USER"
    ;;
    "rm")
        docker stop "epsilon-manual-$USER"
        docker rm -v "epsilon-manual-$USER"
    ;;
    "fixperms")
        fixperms
    ;;
    "exec")
        shift
        docker exec -t -i "epsilon-manual-$USER" $@
        fixperms
    ;;
    "shell")
        shift
        docker exec -i "epsilon-manual-$USER" judgesh -d "/judging/"
        fixperms
    ;;
    "judge")
        shift
        limitjudge
        judging="/judging/$(relpath "$PWD" "$HOME/judging/")"
        docker exec -t -i "epsilon-manual-$USER" judge_exec $judging judge $@
        fixperms
    ;;
    "bash")
        shift
        limitjudge
        judging="/judging/$(relpath "$PWD" "$HOME/judging/")"
        docker exec -t -i "epsilon-manual-$USER" judge_exec $judging bash
        fixperms
    ;;
    *)
        echo "Available commands: create, stop, start, rm, exec, shell, judge, bash"
    ;;
esac
