#!/usr/bin/env python3
import sys, os
import shutil
import glob
import yaml
import stat
import math
from subprocess import Popen, PIPE
DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_PROBLEM = os.path.join(DIR, 'build_problem')

contest = sys.argv[1]

for problem in os.listdir(os.path.join(contest, 'problems')):
    problem_dir = os.path.join(contest, 'problems', problem)
    if os.path.isfile(os.path.join(problem_dir, 'problem.yaml')):
        print('Building problem %s' % problem)
        p = Popen([BUILD_PROBLEM, problem_dir])
        if p.wait() != 0:
            sys.exit(1)

